import PDFDocument from "pdfkit";
import { formatAuDate } from "@/lib/accounting/dates";
import {
  computeLineTotals,
  isFreightLine,
  round2,
  unitPriceInclGst,
} from "@/lib/accounting/invoiceMath";
import type { Invoice } from "@/lib/accounting/invoices";
import {
  INVOICE_BRAND,
  fmtMoney,
  invoiceSubjectLine,
  lessLabel,
} from "@/lib/invoices/invoiceBrand";

export function buildInvoicePdf(invoice: Invoice): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const brand = INVOICE_BRAND;
    const pageW = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const right = doc.page.margins.left + pageW;

    doc.font("Helvetica-Bold").fontSize(16);
    doc.text("TAX INVOICE", { align: "center" });
    doc.moveDown(0.6);
    doc.fontSize(12);
    doc.text(brand.businessName, { align: "center" });
    doc.text(brand.businessAddress, { align: "center" });
    doc.moveDown(0.4);
    doc.text(`ABN: ${brand.abn}`, { align: "center" });
    doc.moveDown(1.2);

    const meta = [
      ["To:", invoice.customerName],
      ["Date:", formatAuDate(invoice.issueDate)],
    ];
    const orderDate = String(invoice.orderDate || "").trim();
    if (orderDate) meta.push(["Order Date:", formatAuDate(orderDate)]);
    meta.push(["Invoice No.:", invoice.number]);
    const subject = invoiceSubjectLine(invoice.subject);
    if (subject) meta.push(["Subject:", subject]);

    for (const [label, value] of meta) {
      const y = doc.y;
      doc.text(label, doc.page.margins.left, y, { width: 90, lineBreak: false });
      doc.text(value, doc.page.margins.left + 95, y, { width: pageW - 95 });
    }

    doc.moveDown(0.8);
    doc.fontSize(10).text("$", { align: "right" });
    doc.moveDown(0.3);
    doc.fontSize(11);

    let subtotalIncl = 0;
    const discounts: Array<{ label: string; amount: number }> = [];

    for (const line of invoice.lines || []) {
      const t = computeLineTotals(line);
      const unitIncl = unitPriceInclGst(line);
      const qty = Number(line.quantity) || 0;
      const desc = String(line.description || "").trim();
      if (t.isDiscount) {
        discounts.push({ label: lessLabel(desc), amount: Math.abs(t.incl) });
        continue;
      }
      subtotalIncl = round2(subtotalIncl + t.incl);
      const y = doc.y;
      if (isFreightLine(line)) {
        doc.text(
          `Freight: ${Math.abs(qty)} x $${fmtMoney(unitIncl)} (incl. GST)`,
          doc.page.margins.left,
          y,
          { width: pageW - 70 }
        );
        doc.text(fmtMoney(t.incl), right - 70, y, { width: 70, align: "right" });
      } else {
        doc.text(String(qty), doc.page.margins.left, y, { width: 36 });
        doc.text(desc, doc.page.margins.left + 40, y, { width: pageW - 200 });
        doc.text(`${fmtMoney(unitIncl)} (incl. GST)`, right - 175, y, {
          width: 100,
        });
        doc.text(fmtMoney(t.incl), right - 70, y, { width: 70, align: "right" });
      }
      doc.moveDown(0.35);
    }

    doc.moveDown(0.8);
    const writeTotal = (label: string, amount: string) => {
      const y = doc.y;
      doc.text(label, doc.page.margins.left, y, { width: pageW - 80 });
      doc.text(amount, right - 70, y, { width: 70, align: "right" });
      doc.moveDown(0.4);
    };
    writeTotal("Subtotal:", fmtMoney(subtotalIncl));
    for (const d of discounts) {
      writeTotal(d.label, fmtMoney(d.amount));
    }
    writeTotal("Total (incl. GST):", fmtMoney(round2(invoice.total)));

    doc.moveDown(1);
    doc.fontSize(12).text("Thank you for your custom", { align: "center" });
    doc.moveDown(1);
    doc.fontSize(11);
    const bank = [
      [`${brand.bankName}:`, brand.bankAccountName],
      ["BSB:", brand.bankBsb],
      ["Account:", brand.bankAccount],
    ];
    for (const [label, value] of bank) {
      const y = doc.y;
      doc.text(label, doc.page.margins.left, y, { width: 90, lineBreak: false });
      doc.text(value, doc.page.margins.left + 95, y);
    }

    doc.moveDown(1.2);
    doc.font("Helvetica").fontSize(9);
    if (invoice.matchKeyword) {
      doc.text(`Payment Reference: ${invoice.matchKeyword}`);
    }
    doc.text("Invoice generated by OzIntel Accounting · ozintel.com.au");
    doc.end();
  });
}
