import { formatAuDate } from "@/lib/accounting/dates";
import {
  computeLineTotals,
  isFreightLine,
  round2,
  unitPriceInclGst,
} from "@/lib/accounting/invoiceMath";
import type { Invoice } from "@/lib/accounting/invoices";
import {
  INVOICE_BRAND,
  displayInvoiceNumber,
  fmtMoney,
  invoiceSubjectLine,
  lessLabel,
} from "@/lib/invoices/invoiceBrand";

function esc(s: string): string {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildInvoiceEmail(invoice: Invoice): {
  subject: string;
  text: string;
  html: string;
} {
  const brand = INVOICE_BRAND;
  const subjectLine = invoiceSubjectLine(invoice.subject);
  const orderDate = String(invoice.orderDate || "").trim();

  let subtotalIncl = 0;
  let discountIncl = 0;
  const productRows: string[] = [];
  const discountRows: string[] = [];
  const textLines: string[] = [];

  for (const line of invoice.lines || []) {
    const t = computeLineTotals(line);
    const unitIncl = unitPriceInclGst(line);
    const qty = Number(line.quantity) || 0;
    const desc = String(line.description || "").trim();
    if (t.isDiscount) {
      discountIncl = round2(discountIncl + Math.abs(t.incl));
      discountRows.push(
        `<tr><td colspan="3">${esc(lessLabel(desc))}</td><td style="text-align:right">${fmtMoney(t.incl)}</td></tr>`
      );
      textLines.push(`${lessLabel(desc)}  ${fmtMoney(t.incl)}`);
    } else {
      subtotalIncl = round2(subtotalIncl + t.incl);
      if (isFreightLine(line)) {
        productRows.push(
          `<tr><td colspan="3">Freight: ${Math.abs(qty)} x $${fmtMoney(unitIncl)} (incl. GST)</td><td style="text-align:right">${fmtMoney(t.incl)}</td></tr>`
        );
        textLines.push(
          `Freight: ${Math.abs(qty)} x $${fmtMoney(unitIncl)} (incl. GST)  ${fmtMoney(t.incl)}`
        );
      } else {
        productRows.push(
          `<tr><td>${qty}</td><td>${esc(desc)}</td><td>${fmtMoney(unitIncl)} (incl. GST)</td><td style="text-align:right">${fmtMoney(t.incl)}</td></tr>`
        );
        textLines.push(
          `${qty}  ${desc}  ${fmtMoney(unitIncl)} (incl. GST)  ${fmtMoney(t.incl)}`
        );
      }
    }
  }

  const totalIncl = round2(invoice.total);
  const addrHtml = esc(brand.businessAddress).replace(/\n/g, "<br/>");

  const html = `<!DOCTYPE html>
<html><body style="font-family:Arial,Helvetica,sans-serif;color:#111;font-size:15px;line-height:1.4">
  <div style="max-width:640px;margin:0 auto">
    <h1 style="text-align:center;font-size:18px;letter-spacing:0.08em">TAX INVOICE</h1>
    <p style="text-align:center;font-weight:bold;margin:0">${esc(brand.businessName)}</p>
    <p style="text-align:center;font-weight:bold;margin:4px 0 0">${addrHtml}</p>
    <p style="text-align:center;font-weight:bold;margin:16px 0 24px">ABN: ${esc(brand.abn)}</p>
    <table style="width:100%;border-collapse:collapse;font-weight:bold">
      <tr><td style="width:8rem">To:</td><td>${esc(invoice.customerName)}</td></tr>
      <tr><td>Date:</td><td>${esc(formatAuDate(invoice.issueDate))}</td></tr>
      ${orderDate ? `<tr><td>Order Date:</td><td>${esc(formatAuDate(orderDate))}</td></tr>` : ""}
      <tr><td>Invoice No.:</td><td>${esc(displayInvoiceNumber(invoice.number))}</td></tr>
      ${subjectLine ? `<tr><td>Subject:</td><td>${esc(subjectLine)}</td></tr>` : ""}
    </table>
    <table style="width:100%;border-collapse:collapse;margin-top:20px">
      ${productRows.join("")}
    </table>
    <p style="margin-top:24px;font-weight:bold">Subtotal: ${fmtMoney(subtotalIncl)}</p>
    ${discountRows.length ? `<table style="width:100%;border-collapse:collapse;font-weight:bold">${discountRows.join("")}</table>` : ""}
    <p style="font-weight:bold">Total (incl. GST): ${fmtMoney(totalIncl)}</p>
    <p style="text-align:center;font-weight:bold;margin:28px 0">Thank you for your custom</p>
    <table style="border-collapse:collapse;font-weight:bold">
      <tr><td style="width:8rem">${esc(brand.bankName)}:</td><td>${esc(brand.bankAccountName)}</td></tr>
      <tr><td>BSB:</td><td>${esc(brand.bankBsb)}</td></tr>
      <tr><td>Account:</td><td>${esc(brand.bankAccount)}</td></tr>
    </table>
    ${invoice.matchKeyword ? `<p style="font-size:12px;margin-top:20px">Payment Reference: ${esc(invoice.matchKeyword)}</p>` : ""}
    <p style="font-size:11px;margin-top:8px">Invoice generated by OzIntel Accounting · ozintel.com.au</p>
  </div>
</body></html>`;

  const text = [
    "TAX INVOICE",
    brand.businessName,
    brand.businessAddress,
    `ABN: ${brand.abn}`,
    "",
    `To: ${invoice.customerName}`,
    `Date: ${formatAuDate(invoice.issueDate)}`,
    orderDate ? `Order Date: ${formatAuDate(orderDate)}` : "",
    `Invoice No.: ${displayInvoiceNumber(invoice.number)}`,
    subjectLine ? `Subject: ${subjectLine}` : "",
    "",
    ...textLines,
    "",
    `Subtotal: ${fmtMoney(subtotalIncl)}`,
    `Total (incl. GST): ${fmtMoney(totalIncl)}`,
    "",
    "Thank you for your custom",
    `${brand.bankName}: ${brand.bankAccountName}`,
    `BSB: ${brand.bankBsb}`,
    `Account: ${brand.bankAccount}`,
    invoice.matchKeyword
      ? `Payment Reference: ${invoice.matchKeyword}`
      : "",
    "Invoice generated by OzIntel Accounting · ozintel.com.au",
  ]
    .filter((line) => line !== "")
    .join("\n");

  return {
    subject: `Tax Invoice ${displayInvoiceNumber(invoice.number)} — ${brand.businessName}`,
    text,
    html,
  };
}
